= Quarkus Fory

include::./includes/attributes.adoc[]

Integrates with the Apache Fory serialization framework. https://github.com/apache/fory[Apache Fory] is a blazingly fast multi-language serialization framework powered by JIT and zero-copy. With the `quarkus-fory` extension, users can use fast and easy-to-use serialization feature provided by Apache Fory out-of-box.


== Installation

If you want to use this extension, you need to add the `io.quarkiverse.fory:quarkus-fory` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.fory</groupId>
    <artifactId>quarkus-fory</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

If you want to use Apache Fory to serialize your objects, you need to use `@Inject` to get an instance of `Fory` to serialize your objects. `Fory` instance is created by `quarkus-fory` at build time, you don't need to create `Fory` by yourself.
And you also need to mark your classes for serialization.

For instance, the following code is an example using `@Inject` and `@ForySerialization` annotation to serialize a JDK 17+ `record` object.

[source,java,subs=attributes+]
----
import java.util.List;
import java.util.Map;

import io.quarkiverse.fory.ForySerialization;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

import org.apache.fory.BaseFory;

@ForySerialization
record Foo(int f1, String f2, List<String> f3, Map<String, Long> f4) {
}

@Path("/fory")
@ApplicationScoped
public class ForyResources {
  @Inject
  BaseFory fory;

  @GET
  @Path("/record")
  public Boolean testSerializeFooRecord() {
    Foo foo1 = new Foo(10, "abc", List.of("str1", "str2"), Map.of("k1", 10L, "k2", 20L));
    Foo foo2 = (Foo) fory.deserialize(fory.serialize(foo1));
    return foo1.equals(foo2);
  }
}
----

You can also mark a class for serialization by `application.properties` configurations.

[source,properties,subs=attributes+]
----
quarkus.fory.register-class-names=io.demo.Foo,io.demo.Bar
----

If you want to specify class id or serializer for a class, you can do it by annotation:

[source,java,subs=attributes+]
----
import io.quarkiverse.fory.ForySerialization;

@ForySerialization(classId = 200, serializer = FooSerializer.class)
record Foo(int f1, String f2, List<String> f3, Map<String, Long> f4) {
}
----

If the class is a third-party class which you can't add annotation, you can specify the `targetClasses` property:
[source,java,subs=attributes+]
----
import io.quarkiverse.fory.ForySerialization;

@ForySerialization(classId = 200, serializer = FooSerializer.class, targetClasses = Foo.class)
public class FooConfig {
}
----

Or you can configure by `application.properties` configurations.

[source,properties,subs=attributes+]
----
quarkus.fory.register-class."io.demo.Foo".class-id=200
quarkus.fory.register-class."io.demo.Foo".serializer=io.demo.FooSerializer
----

For about how to create a customized Fory serializer for a class, see https://fory.apache.org/docs/guide/java_object_graph_guide#implement-a-customized-serializer[Apache Fory document]

== Integartion in Quarkus REST/RESTEasy

It enables efficient and structured data exchange between client and server using the fory during serialization and deserialization with `application/fory` media type. 
Example for a JAX-RS endpoint on the server side like:

[source,java,subs=attributes+]
----
@Path("/example")
@Produces("application/fory")
@Consumes("application/fory")
public class ExampleResource {
    @POST
    public Foo test(Foo obj) {
       return new Foo(1, "test");
    }
}
----

NOTE: If class registration is enabled, the class ID (or serialization identifier) must be identical on both the client and server sides. A mismatch in the class ID will result in serialization or deserialization issues, potentially causing runtime errors or data corruption.
If class registration is disabled, please do not assign class id at client and server slides.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-fory.adoc[leveloffset=+1,opts=optional]
