# JSON serialization does not require class registration
quarkus.fory.required-class-registration=false

quarkus.fory.json.enabled=true

quarkus.rest-client."io.quarkiverse.fory.it.json.JsonClient".url=${test.url}
